### ISSUE TITLE
KDE Runtime 5.15-23.08 support

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration#16]
New version of 5.x, so we'll have to go through the entire rigmarole once again.

**Comment by Eonfge** [comment]
related to: https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform/issues/18

**Comment by grulja** [comment]
Done.

**Comment by ghost** [comment]
@grulja Does this plugin need to be updated to the latest version of KDE Runtime 5.15 series?

**Comment by travier** [comment]
We don't need it starting with Qt 6.6. See: https://invent.kde.org/teams/flathub/issues/-/issues/26:

> No Qt6.6 branch:
> WaylandDecoration.QGnomePlatform-decoration:
> https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration: Deprecated in favor of QAdwaitaDecorations
