### ISSUE TITLE
Updated KeePassXC to 5.15 and now themes don't work under wayland (is 5.15 unavailable?)

### ISSUE THREAD

**Issue by AsavarTzeth** [flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration#2]
I updated KeePassXC yesterday and noticed that it required newer versions of dependencies that come with the Sdk. So I had to update to 5.15.

However if I run the app in my Gnome wayland session it uses some default Qt theme, not Adwaita. If I start an Xorg session, everything works fine though.

I then notice that there are no 5.15 versions of org.kde.PlatformTheme.QGnomePlatform or org.kde.WaylandDecoration.QGnomePlatform-decoration available on flathub and start to wonder, especially about this one since it only broke with wayland.

Are these necessary components now merged and included elsewhere?
Am I supposed to wait for an update to this?
Or is there are better place to report and follow this?

![Skärmbild från 2020-09-03 07-03-37](https://user-images.githubusercontent.com/6402411/92073446-f1360680-edb3-11ea-957f-a345a86c51ab.png)

**Comment by Siosm** [comment]
The following branches have been pushed:

- https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform/tree/branch/5.15
- https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration/tree/branch/5.15

This should resolve this issue. Let us know if it's not the case.
