### ISSUE TITLE
v6.3 - undefined symbol: qt_resourceFeatureZstd, version Qt_6

### ISSUE THREAD

**Issue by fabiscafe** [flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration#4]
If I start up ProtonUp-Qt. I get no window decoration and in the log `QT_DEBUG_PLUGINS=1 flatpak run net.davidotek.pupgui2` this output:

    qt.core.library: "/usr/share/runtime/lib/plugins/QGnomePlatform-decoration/wayland-decoration-client/libqgnomeplatformdecoration.so" cannot load: Cannot load library /usr/share/runtime/lib/plugins/QGnomePlatform-decoration/wayland-decoration-client/libqgnomeplatformdecoration.so: (/usr/share/runtime/lib/plugins/Adwaita/lib/libadwaitaqt6.so.1: undefined symbol: qt_resourceFeatureZstd, version Qt_6)
    qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/usr/share/runtime/lib/plugins/QGnomePlatform-decoration/wayland-decoration-client/libqgnomeplatformdecoration.so" : "Cannot load library /usr/share/runtime/lib/plugins/QGnomePlatform-decoration/wayland-decoration-client/libqgnomeplatformdecoration.so: (/usr/share/runtime/lib/plugins/Adwaita/lib/libadwaitaqt6.so.1: undefined symbol: qt_resourceFeatureZstd, version Qt_6)"
    Could not create decoration from factory! Running with no decorations.

If I uninstall 'runtime/org.kde.WaylandDecoration.QGnomePlatform-decoration/x86_64/6.3' it defaults back to Qt build-in windecoration that works.

This is on a GNOME 42 desktop running Arch/Fedora.

I'm not entirely sure if this is the right spot to report it to. Sorry if it is not. :)

**Comment by grulja** [comment]
I can reproduce, but when I try another application using Qt 6.3 it works (I just built one against Qt 6.3.1). Maybe ProtonUp-Qt needs to be rebuild? I don't know against what Qt 6.3 version it was built, but I can see last time it was updated it was around the time when Qt 6.3.1 went to the KDE SDK.

**Comment by travier** [comment]
Probably best reported at https://github.com/flathub/net.davidotek.pupgui2 then

**Comment by fabiscafe** [comment]
Thanks. Looks like this is known: https://github.com/DavidoTek/ProtonUp-Qt/issues/98

I'll close this one here :+1:
